### ISSUE TITLE
excel menu

### ISSUE THREAD

**Issue by scyr-t** [EszopiCoder/excel-barcode-fx-library#1]
After add your project and close excel when open excel no option in ribon menu

![Sans titre](https://user-images.githubusercontent.com/91289734/134580838-56908ec1-d64e-4e3e-89d2-1a21a2b5a957.jpg)
u

**Comment by EszopiCoder** [comment]
Have you tried manually customizing the ribbon?
Click "File" (Fichier) -> "Options" (bottom left corner) -> "Customize Ribbon" -> Select "All Commands"
The commands "Barcode Functions", "Update Barcodes", and "Help" should be there
Let me know if this works!
![Capture](https://user-images.githubusercontent.com/55963065/134615417-799a6ff1-a5f1-4753-a5bd-fc33bcc6a083.PNG)

**Comment by scyr-t** [comment]
I have not this opti
![Sans titre](https://user-images.githubusercontent.com/91289734/134732088-bcaad66e-33d0-4207-8fc5-e2cfb8956c33.png)
on

**Comment by EszopiCoder** [comment]
Sorry for the late reply - Is it only the menu that is not appearing? Can you still use the functions?
Can you try switching the language to English and reinstall the add-in?

**Comment by scyr-t** [comment]
Function not working
![Sans titre 3](https://user-images.githubusercontent.com/91289734/135174570-b3c3931c-ac80-4f0f-9294-7b590bd141e5.png)

**Comment by EszopiCoder** [comment]
I think you typed the function wrong. It should just be `=UPCA(A1)`

**Comment by scyr-t** [comment]
SAmeting

![Sans titre 4](https://user-images.githubusercontent.com/91289734/135297542-2a1b9863-41b9-46f3-bc49-90859e7ddae6.png)

**Comment by EszopiCoder** [comment]
After installing the add-in, can you open the Visual Basic editor (Alt + F11) and see the code?

**Comment by scyr-t** [comment]
yes 
![Sans titre 10](https://user-images.githubusercontent.com/91289734/135874684-51ae9e80-7763-404d-8068-dd4ad4d39a0d.png)
But if i close excel and reopen it
![Sans titre 11](https://user-images.githubusercontent.com/91289734/135874723-0e46c1b3-315e-4ea2-babb-f88808b1234b.png)
Same probleme with another computer

**Comment by EszopiCoder** [comment]
Do other Excel add-ins have this same issue?

**Comment by scyr-t** [comment]
no error with other add-in. I have two computer and same problem on other computer

**Comment by EszopiCoder** [comment]
Try following the steps listed in this article: https://jkp-ads.com/articles/excel-add-ins-fail-to-load.asp

**Comment by scyr-t** [comment]
Sorry for the delay. I tried the solution and it works. Thank you. Nice day
